[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:meilisearch]
# We point the database to save in /data/meili_data (crucial for HF persistent storage)
command=./meilisearch --http-addr 127.0.0.1:7700 --db-path /data/meili_data
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

# [program:fastapi]
# This runs the health check server on port 7860 for Hugging Face
# command=uvicorn health_server:app --host 0.0.0.0 --port 7860
# autostart=true
# autorestart=true
# stdout_logfile=/dev/fd/1
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/fd/2
# stderr_logfile_maxbytes=0

[program:listener]
command=python -m scraper.listener
autostart=true
autorestart=true
# Wait 5 seconds before starting so Meilisearch has time to boot up
startsecs=5 
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:bot]
command=python -m bot.main_bot
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0